spring:
  application:
    name: restaurant

  datasource:
    url: jdbc:tracing:postgresql://localhost:5432/Restaurant
    username: postgres
    password: Tsunami9
    driver-class-name: io.opentracing.contrib.jdbc.TracingDriver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog-master.yml

  zipkin:
    base-url: http://localhost:9411

restaurant:
  tracing:
    sql:
      enabled: true

keycloak:
  realm: restaurant
  resource: restaurant-api
  auth-server-url: http://localhost:8180/auth
  bearer-only: true
  principal-attribute: preferred_username
