spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Restaurant
    username: postgres
    password: Tsunami9
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog-master.yml

  hateoas:
    use-hal-as-default-json-media-type: false