spring:
  application:
    name: restaurant

  datasource:
    url: jdbc:postgresql://localhost:5432/Restaurant
    username: postgres
    password: Tsunami9
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog-master.yml

keycloak:
  realm: restaurant
  resource: restaurant-api
  auth-server-url: http://localhost:8180/auth
  bearer-only: true
  principal-attribute: preferred_username
